### ISSUE TITLE
July 22, 2020

### ISSUE THREAD

**Issue by iennae** [osscda/cloud-native-stream#10]
Last Week
Review project so far, revisit Dapr concepts of service invocation and state management
Refactored the javascript for the /neworder with the help of @bnb switched from promises to async and await. 

This week
Continue working on the neworder API. 

- last week we reviewed our progress
- two weeks ago, we discovered that the orders API was just storing one order. THE HUMANITY!
- last week, we started to fix the refactor that we did _two_ weeks ago.
- we discovered some super thorny grungy promises code
- @bnb helped us with the grungy code and add some `async`/`await` to our lives
- TIERNEY IS BAAAACK today to help us do some more goodness

**Comment by arschles** [comment]
Tierney's TIL:
in the YAML for a GitHub action,
you can use this variable to get the 
default branch: $default_branch

Jennifer's TIL/ICYMI:
A new, awesome DevRel person has just joined GitHub. (see her [here](https://twitter.com/FeyNudibranch))
She has a ton of awesome experience in the Puppet community, and she will have a ton of worldwide impact at GitHub and generally in many/all open source communities

Aaron's TIL/ICYMI:
Bracket Tab Colorizer VSCode extension
Twitch streamers: erikdotdev and beginbot
